# Generated by Django 6.0.2 on 2026-02-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certificate_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='experiences/logos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
