# Generated by Django 6.0.2 on 2026-02-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_experience_logo_project_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_featured',
            new_name='featured',
        ),
    ]
