# Generated by Django 6.0.2 on 2026-02-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('planned', 'Planned')], default='completed', max_length=20),
        ),
    ]
